#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LauncherData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SWGANH_Servers")]
	public partial class LauncherDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttCustomTre(tCustomTre instance);
    partial void UpdatetCustomTre(tCustomTre instance);
    partial void DeletetCustomTre(tCustomTre instance);
    partial void InserttServer(tServer instance);
    partial void UpdatetServer(tServer instance);
    partial void DeletetServer(tServer instance);
    partial void InserttStandardTre(tStandardTre instance);
    partial void UpdatetStandardTre(tStandardTre instance);
    partial void DeletetStandardTre(tStandardTre instance);
    #endregion
		
		public LauncherDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SWGANH_ServersConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LauncherDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LauncherDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LauncherDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LauncherDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tLauncherVersion> tLauncherVersions
		{
			get
			{
				return this.GetTable<tLauncherVersion>();
			}
		}
		
		public System.Data.Linq.Table<tCustomTre> tCustomTres
		{
			get
			{
				return this.GetTable<tCustomTre>();
			}
		}
		
		public System.Data.Linq.Table<tServer> tServers
		{
			get
			{
				return this.GetTable<tServer>();
			}
		}
		
		public System.Data.Linq.Table<tStandardTre> tStandardTres
		{
			get
			{
				return this.GetTable<tStandardTre>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tLauncherVersion")]
	public partial class tLauncherVersion
	{
		
		private System.Guid _VersionId;
		
		private string _VersionNumber;
		
		private System.DateTime _DateCreated;
		
		private string _PatchNotes;
		
		private string _DownloadPath;
		
		public tLauncherVersion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid VersionId
		{
			get
			{
				return this._VersionId;
			}
			set
			{
				if ((this._VersionId != value))
				{
					this._VersionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this._VersionNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatchNotes", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string PatchNotes
		{
			get
			{
				return this._PatchNotes;
			}
			set
			{
				if ((this._PatchNotes != value))
				{
					this._PatchNotes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DownloadPath", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DownloadPath
		{
			get
			{
				return this._DownloadPath;
			}
			set
			{
				if ((this._DownloadPath != value))
				{
					this._DownloadPath = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tCustomTre")]
	public partial class tCustomTre : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _CustomTreId;
		
		private System.Guid _ServerId;
		
		private string _Name;
		
		private string _Uri;
		
		private string _MD5;
		
		private EntityRef<tServer> _tServer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomTreIdChanging(System.Guid value);
    partial void OnCustomTreIdChanged();
    partial void OnServerIdChanging(System.Guid value);
    partial void OnServerIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnUriChanging(string value);
    partial void OnUriChanged();
    partial void OnMD5Changing(string value);
    partial void OnMD5Changed();
    #endregion
		
		public tCustomTre()
		{
			this._tServer = default(EntityRef<tServer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomTreId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid CustomTreId
		{
			get
			{
				return this._CustomTreId;
			}
			set
			{
				if ((this._CustomTreId != value))
				{
					this.OnCustomTreIdChanging(value);
					this.SendPropertyChanging();
					this._CustomTreId = value;
					this.SendPropertyChanged("CustomTreId");
					this.OnCustomTreIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ServerId
		{
			get
			{
				return this._ServerId;
			}
			set
			{
				if ((this._ServerId != value))
				{
					if (this._tServer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnServerIdChanging(value);
					this.SendPropertyChanging();
					this._ServerId = value;
					this.SendPropertyChanged("ServerId");
					this.OnServerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uri", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Uri
		{
			get
			{
				return this._Uri;
			}
			set
			{
				if ((this._Uri != value))
				{
					this.OnUriChanging(value);
					this.SendPropertyChanging();
					this._Uri = value;
					this.SendPropertyChanged("Uri");
					this.OnUriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MD5", DbType="NChar(16) NOT NULL", CanBeNull=false)]
		public string MD5
		{
			get
			{
				return this._MD5;
			}
			set
			{
				if ((this._MD5 != value))
				{
					this.OnMD5Changing(value);
					this.SendPropertyChanging();
					this._MD5 = value;
					this.SendPropertyChanged("MD5");
					this.OnMD5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tServer_tCustomTre", Storage="_tServer", ThisKey="ServerId", OtherKey="ServerId", IsForeignKey=true)]
		public tServer tServer
		{
			get
			{
				return this._tServer.Entity;
			}
			set
			{
				tServer previousValue = this._tServer.Entity;
				if (((previousValue != value) 
							|| (this._tServer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tServer.Entity = null;
						previousValue.tCustomTres.Remove(this);
					}
					this._tServer.Entity = value;
					if ((value != null))
					{
						value.tCustomTres.Add(this);
						this._ServerId = value.ServerId;
					}
					else
					{
						this._ServerId = default(System.Guid);
					}
					this.SendPropertyChanged("tServer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tServer")]
	public partial class tServer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ServerId;
		
		private string _Name;
		
		private string _Description;
		
		private string _Address;
		
		private int _Port;
		
		private string _NewsUrl;
		
		private System.DateTime _LastUpdated;
		
		private int _Population;
		
		private int _CharsCreated;
		
		private int _LauncherPort;
		
		private EntitySet<tCustomTre> _tCustomTres;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnServerIdChanging(System.Guid value);
    partial void OnServerIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPortChanging(int value);
    partial void OnPortChanged();
    partial void OnNewsUrlChanging(string value);
    partial void OnNewsUrlChanged();
    partial void OnLastUpdatedChanging(System.DateTime value);
    partial void OnLastUpdatedChanged();
    partial void OnPopulationChanging(int value);
    partial void OnPopulationChanged();
    partial void OnCharsCreatedChanging(int value);
    partial void OnCharsCreatedChanged();
    partial void OnLauncherPortChanging(int value);
    partial void OnLauncherPortChanged();
    #endregion
		
		public tServer()
		{
			this._tCustomTres = new EntitySet<tCustomTre>(new Action<tCustomTre>(this.attach_tCustomTres), new Action<tCustomTre>(this.detach_tCustomTres));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ServerId
		{
			get
			{
				return this._ServerId;
			}
			set
			{
				if ((this._ServerId != value))
				{
					this.OnServerIdChanging(value);
					this.SendPropertyChanging();
					this._ServerId = value;
					this.SendPropertyChanged("ServerId");
					this.OnServerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Port", DbType="Int NOT NULL")]
		public int Port
		{
			get
			{
				return this._Port;
			}
			set
			{
				if ((this._Port != value))
				{
					this.OnPortChanging(value);
					this.SendPropertyChanging();
					this._Port = value;
					this.SendPropertyChanged("Port");
					this.OnPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsUrl", DbType="NVarChar(255)")]
		public string NewsUrl
		{
			get
			{
				return this._NewsUrl;
			}
			set
			{
				if ((this._NewsUrl != value))
				{
					this.OnNewsUrlChanging(value);
					this.SendPropertyChanging();
					this._NewsUrl = value;
					this.SendPropertyChanged("NewsUrl");
					this.OnNewsUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime LastUpdated
		{
			get
			{
				return this._LastUpdated;
			}
			set
			{
				if ((this._LastUpdated != value))
				{
					this.OnLastUpdatedChanging(value);
					this.SendPropertyChanging();
					this._LastUpdated = value;
					this.SendPropertyChanged("LastUpdated");
					this.OnLastUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Population", DbType="Int NOT NULL")]
		public int Population
		{
			get
			{
				return this._Population;
			}
			set
			{
				if ((this._Population != value))
				{
					this.OnPopulationChanging(value);
					this.SendPropertyChanging();
					this._Population = value;
					this.SendPropertyChanged("Population");
					this.OnPopulationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CharsCreated", DbType="Int NOT NULL")]
		public int CharsCreated
		{
			get
			{
				return this._CharsCreated;
			}
			set
			{
				if ((this._CharsCreated != value))
				{
					this.OnCharsCreatedChanging(value);
					this.SendPropertyChanging();
					this._CharsCreated = value;
					this.SendPropertyChanged("CharsCreated");
					this.OnCharsCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LauncherPort", DbType="Int NOT NULL")]
		public int LauncherPort
		{
			get
			{
				return this._LauncherPort;
			}
			set
			{
				if ((this._LauncherPort != value))
				{
					this.OnLauncherPortChanging(value);
					this.SendPropertyChanging();
					this._LauncherPort = value;
					this.SendPropertyChanged("LauncherPort");
					this.OnLauncherPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tServer_tCustomTre", Storage="_tCustomTres", ThisKey="ServerId", OtherKey="ServerId")]
		public EntitySet<tCustomTre> tCustomTres
		{
			get
			{
				return this._tCustomTres;
			}
			set
			{
				this._tCustomTres.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tCustomTres(tCustomTre entity)
		{
			this.SendPropertyChanging();
			entity.tServer = this;
		}
		
		private void detach_tCustomTres(tCustomTre entity)
		{
			this.SendPropertyChanging();
			entity.tServer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tStandardTre")]
	public partial class tStandardTre : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _StandardTreId;
		
		private string _Filename;
		
		private string _MD5;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStandardTreIdChanging(System.Guid value);
    partial void OnStandardTreIdChanged();
    partial void OnFilenameChanging(string value);
    partial void OnFilenameChanged();
    partial void OnMD5Changing(string value);
    partial void OnMD5Changed();
    #endregion
		
		public tStandardTre()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardTreId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid StandardTreId
		{
			get
			{
				return this._StandardTreId;
			}
			set
			{
				if ((this._StandardTreId != value))
				{
					this.OnStandardTreIdChanging(value);
					this.SendPropertyChanging();
					this._StandardTreId = value;
					this.SendPropertyChanged("StandardTreId");
					this.OnStandardTreIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filename", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Filename
		{
			get
			{
				return this._Filename;
			}
			set
			{
				if ((this._Filename != value))
				{
					this.OnFilenameChanging(value);
					this.SendPropertyChanging();
					this._Filename = value;
					this.SendPropertyChanged("Filename");
					this.OnFilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MD5", DbType="NChar(16) NOT NULL", CanBeNull=false)]
		public string MD5
		{
			get
			{
				return this._MD5;
			}
			set
			{
				if ((this._MD5 != value))
				{
					this.OnMD5Changing(value);
					this.SendPropertyChanging();
					this._MD5 = value;
					this.SendPropertyChanged("MD5");
					this.OnMD5Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
